package com.hezae.apam.ui.Themes.Mica

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val MicaDarkColorScheme = darkColorScheme(
    primary = Color(0xFF90CAF9),
    onPrimary = Color.Black,
    primaryContainer = Color(0xFF0D47A1),
    onPrimaryContainer = Color.White,
    inversePrimary = Color(0xFF95BD94),
    secondary = Color(0xFFB2EBF2),
    onSecondary = Color.Black,
    secondaryContainer = Color(0xFF006064),
    onSecondaryContainer = Color.White,
    tertiary = Color(0xFFB2EBF2),
    onTertiary = Color.Black,
    tertiaryContainer = Color(0xFF80DEEA),
    onTertiaryContainer = Color.Black,
    background = Color(0xFF725F5F),
    onBackground = Color.White,
    surface = Color(0xFF263238),
    onSurface = Color.White,
    surfaceVariant = Color(0xFF37474F),
    onSurfaceVariant = Color.White,
    surfaceTint = Color(0xFF90CAF9),
    inverseSurface = Color(0xFFECEFF1),
    inverseOnSurface = Color.Black,
    error = Color(0xFFD32F2F),
    onError = Color.White,
    errorContainer = Color(0xFFF9BBAE),
    onErrorContainer = Color.White,
    outline = Color(0xFFB0B0B0),
    outlineVariant = Color(0xFFD0D0D0),
    scrim = Color(0xFF000000).copy(alpha = 0.32f),
    surfaceBright = Color(0xFF37474F),
    surfaceContainer = Color(0xFF90CAF9),
    surfaceContainerHigh = Color(0xFFB3E5FC),
    surfaceContainerHighest = Color(0xFF212121),
    surfaceContainerLow = Color(0xFF424242),
    surfaceContainerLowest = Color(0xFFFAFAFA),
    surfaceDim = Color(0xFFB0B0B0).copy(alpha = 0.2f)
)



val MicaLightColorScheme = lightColorScheme(
    primary = Color(0xFF207FCF),
    onPrimary = Color(0xFFDAE3EF),
    primaryContainer = Color(0xFFBBDEFB),
    onPrimaryContainer = Color(0xFFDAE3EF),
    inversePrimary = Color(0xFF21937C),
    secondary = Color(0xFF6290C2),
    onSecondary = Color(0xFFDAE3EF),
    secondaryContainer = Color(0xFF6290C2),
    onSecondaryContainer = Color(0xFFDAE3EF),
    tertiary = Color(0xFFBBDEFB),
    onTertiary = Color(0xFFDAE3EF),
    tertiaryContainer = Color(0xFFE1F5FE),
    onTertiaryContainer = Color(0xFFDAE3EF),
    background = Color(0xFFF1F1F1),
    onBackground = Color(0xFF6290C2),
    surface = Color(0xFF6290C2),
    onSurface = Color(0xFFEFEEEE),
    surfaceVariant = Color(0xC16290C2),
    onSurfaceVariant = Color(0xFFDAE3EF),
    surfaceTint = Color(0xFFB3E5FC),
    inverseSurface = Color(0xFF1A1A1A),
    inverseOnSurface = Color(0xFFDAE3EF),
    error = Color(0xFFD32F2F),
    onError = Color(0xFFDAE3EF),
    errorContainer = Color(0xFFF9BBAE),
    onErrorContainer = Color(0xFFDAE3EF),
    outline = Color(0xFFB0B0B0),
    outlineVariant = Color(0xFFD0D0D0),
    scrim = Color(0xFF000000).copy(alpha = 0.32f),
    surfaceBright = Color(0xFFE3F2FD),
    surfaceContainer = Color(0xFFACCAE5),
    surfaceContainerHigh = Color(0xB26290C2),
    surfaceContainerHighest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFE1F5FE),
    surfaceContainerLowest = Color(0xFFFAFAFA),
    surfaceDim = Color(0xFFB0B0B0).copy(alpha = 0.2f)
)

